### ISSUE TITLE
Invalid syntax, wittyPy/wittyPy.py, line 167

### ISSUE THREAD

**Issue by phaedrusalt** [elpunkt/wittyPy#1]
Little "oopsie" here:

  File "wittyPy/wittyPy.py", line 167
    def __init__(self, *args, name=None):
                                        ^
SyntaxError: invalid syntax

**Comment by phaedrusalt** [comment]
Fix:
Lines 166/167
    def __init__(self, *args, **kwargs):
        self.name = kwargs[name]

(I would have fixed the code here, but I have not tested this fix.  Time permitting I will do so soon.)

**Comment by kon-foo** [comment]
Thanks for the info and sorry for the late response. I guess you are using Python 2?! Because in Python >3 this is valid syntax. Can you confirm that the rest of wittyPy is working for you with Python 2? In that case I would be happy to add Python 2 to the version list in implement your proposed fix.
